### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [ddoubleo/xorCoder#1]
1. Не хватает тестов
2. Для xor-кодирования можно обойтись без хранения всего файла в памяти в процессе.

**Comment by gagarski** [comment]
1. Тесты должны запускаться не только на вашем компьютере, а где угодно. Используйте относительные пути с `/`
2. Ещё есть такой баг, что при переносе строки вы начинаете чтение ключа сначала. То есть для файла:
`aa
bb
`

    и ключа `abcd0011` вы половину ключа просто не используете.

**Comment by ddoubleo** [comment]
Все поправил, теперь использую относительные пути, по ключу теперь полностью прохожу.
